/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TratamentosRouteImport } from './routes/tratamentos'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as TratamentosIndexRouteImport } from './routes/tratamentos.index'
import { Route as TratamentosCategoriaRouteImport } from './routes/tratamentos.$categoria'
import { Route as TratamentosCategoriaIndexRouteImport } from './routes/tratamentos.$categoria.index'
import { Route as TratamentosCategoriaSlugRouteImport } from './routes/tratamentos.$categoria.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TratamentosRoute = TratamentosRouteImport.update({
  id: '/tratamentos',
  path: '/tratamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TratamentosIndexRoute = TratamentosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TratamentosRoute,
} as any)
const TratamentosCategoriaRoute = TratamentosCategoriaRouteImport.update({
  id: '/$categoria',
  path: '/$categoria',
  getParentRoute: () => TratamentosRoute,
} as any)
const TratamentosCategoriaIndexRoute =
  TratamentosCategoriaIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => TratamentosCategoriaRoute,
  } as any)
const TratamentosCategoriaSlugRoute =
  TratamentosCategoriaSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => TratamentosCategoriaRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tratamentos': typeof TratamentosRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/tratamentos/$categoria': typeof TratamentosCategoriaRouteWithChildren
  '/blog/': typeof BlogIndexRoute
  '/tratamentos/': typeof TratamentosIndexRoute
  '/tratamentos/$categoria/$slug': typeof TratamentosCategoriaSlugRoute
  '/tratamentos/$categoria/': typeof TratamentosCategoriaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog': typeof BlogIndexRoute
  '/tratamentos': typeof TratamentosIndexRoute
  '/tratamentos/$categoria/$slug': typeof TratamentosCategoriaSlugRoute
  '/tratamentos/$categoria': typeof TratamentosCategoriaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/tratamentos': typeof TratamentosRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/tratamentos/$categoria': typeof TratamentosCategoriaRouteWithChildren
  '/blog/': typeof BlogIndexRoute
  '/tratamentos/': typeof TratamentosIndexRoute
  '/tratamentos/$categoria/$slug': typeof TratamentosCategoriaSlugRoute
  '/tratamentos/$categoria/': typeof TratamentosCategoriaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/tratamentos'
    | '/blog/$slug'
    | '/tratamentos/$categoria'
    | '/blog/'
    | '/tratamentos/'
    | '/tratamentos/$categoria/$slug'
    | '/tratamentos/$categoria/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog/$slug'
    | '/blog'
    | '/tratamentos'
    | '/tratamentos/$categoria/$slug'
    | '/tratamentos/$categoria'
  id:
    | '__root__'
    | '/'
    | '/tratamentos'
    | '/blog/$slug'
    | '/tratamentos/$categoria'
    | '/blog/'
    | '/tratamentos/'
    | '/tratamentos/$categoria/$slug'
    | '/tratamentos/$categoria/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TratamentosRoute: typeof TratamentosRouteWithChildren
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tratamentos': {
      id: '/tratamentos'
      path: '/tratamentos'
      fullPath: '/tratamentos'
      preLoaderRoute: typeof TratamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tratamentos/': {
      id: '/tratamentos/'
      path: '/'
      fullPath: '/tratamentos/'
      preLoaderRoute: typeof TratamentosIndexRouteImport
      parentRoute: typeof TratamentosRoute
    }
    '/tratamentos/$categoria': {
      id: '/tratamentos/$categoria'
      path: '/$categoria'
      fullPath: '/tratamentos/$categoria'
      preLoaderRoute: typeof TratamentosCategoriaRouteImport
      parentRoute: typeof TratamentosRoute
    }
    '/tratamentos/$categoria/': {
      id: '/tratamentos/$categoria/'
      path: '/'
      fullPath: '/tratamentos/$categoria/'
      preLoaderRoute: typeof TratamentosCategoriaIndexRouteImport
      parentRoute: typeof TratamentosCategoriaRoute
    }
    '/tratamentos/$categoria/$slug': {
      id: '/tratamentos/$categoria/$slug'
      path: '/$slug'
      fullPath: '/tratamentos/$categoria/$slug'
      preLoaderRoute: typeof TratamentosCategoriaSlugRouteImport
      parentRoute: typeof TratamentosCategoriaRoute
    }
  }
}

interface TratamentosCategoriaRouteChildren {
  TratamentosCategoriaSlugRoute: typeof TratamentosCategoriaSlugRoute
  TratamentosCategoriaIndexRoute: typeof TratamentosCategoriaIndexRoute
}

const TratamentosCategoriaRouteChildren: TratamentosCategoriaRouteChildren = {
  TratamentosCategoriaSlugRoute: TratamentosCategoriaSlugRoute,
  TratamentosCategoriaIndexRoute: TratamentosCategoriaIndexRoute,
}

const TratamentosCategoriaRouteWithChildren =
  TratamentosCategoriaRoute._addFileChildren(TratamentosCategoriaRouteChildren)

interface TratamentosRouteChildren {
  TratamentosCategoriaRoute: typeof TratamentosCategoriaRouteWithChildren
  TratamentosIndexRoute: typeof TratamentosIndexRoute
}

const TratamentosRouteChildren: TratamentosRouteChildren = {
  TratamentosCategoriaRoute: TratamentosCategoriaRouteWithChildren,
  TratamentosIndexRoute: TratamentosIndexRoute,
}

const TratamentosRouteWithChildren = TratamentosRoute._addFileChildren(
  TratamentosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TratamentosRoute: TratamentosRouteWithChildren,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
