name: Deploy via FTP Locaweb

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build & FTP Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Instalar dependências e Gerar Build
        run: |
          npm ci
          npm run build

      - name: FTP Deploy Locaweb
        uses: locaweb/ftp-deploy@1.0.0
        with:
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USER }}
          password: ${{ secrets.PASS }}
          localDir: "dist"
          # remoteDir: "public_html" # Descomente e ajuste se a Locaweb indicar uma subpasta específica